// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCArP-w34CoHKSRyhjkcEh1oZ_8_31Skpk',
    appId: '1:245026725201:web:3266bcf2948f82ec1b4770',
    messagingSenderId: '245026725201',
    projectId: 'turfbooking-8d98c',
    authDomain: 'turfbooking-8d98c.firebaseapp.com',
    databaseURL: 'https://turfbooking-8d98c-default-rtdb.firebaseio.com',
    storageBucket: 'turfbooking-8d98c.firebasestorage.app',
    measurementId: 'G-C97NHMJ2FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOcKGjh5S5t9aEp4pt0041b6tCcDcz23M',
    appId: '1:245026725201:android:267b578bcceb14fd1b4770',
    messagingSenderId: '245026725201',
    projectId: 'turfbooking-8d98c',
    databaseURL: 'https://turfbooking-8d98c-default-rtdb.firebaseio.com',
    storageBucket: 'turfbooking-8d98c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGppfeS1EecOuoTD6NTaWI8Qo0uhQpIY',
    appId: '1:245026725201:ios:abc1fa2fd1d9c4df1b4770',
    messagingSenderId: '245026725201',
    projectId: 'turfbooking-8d98c',
    databaseURL: 'https://turfbooking-8d98c-default-rtdb.firebaseio.com',
    storageBucket: 'turfbooking-8d98c.firebasestorage.app',
    iosBundleId: 'com.example.turfBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGppfeS1EecOuoTD6NTaWI8Qo0uhQpIY',
    appId: '1:245026725201:ios:abc1fa2fd1d9c4df1b4770',
    messagingSenderId: '245026725201',
    projectId: 'turfbooking-8d98c',
    databaseURL: 'https://turfbooking-8d98c-default-rtdb.firebaseio.com',
    storageBucket: 'turfbooking-8d98c.firebasestorage.app',
    iosBundleId: 'com.example.turfBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCArP-w34CoHKSRyhjkcEh1oZ_8_31Skpk',
    appId: '1:245026725201:web:0402ab33d1bd03091b4770',
    messagingSenderId: '245026725201',
    projectId: 'turfbooking-8d98c',
    authDomain: 'turfbooking-8d98c.firebaseapp.com',
    databaseURL: 'https://turfbooking-8d98c-default-rtdb.firebaseio.com',
    storageBucket: 'turfbooking-8d98c.firebasestorage.app',
    measurementId: 'G-CHQNG02629',
  );
}
